### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Max-Well-Wang** [Kibeom-Hong/Domain-Aware-Style-Transfer#3]
Hello, I have the following problems when I run the main.py file. Can you help me solve it? 
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/ymq/Domain-Aware-Style-Transfer-main/Domain-Aware-Style-Transfer-main/main.py", line 68, in <module>
    model = Baseline(args)
  File "C:\Users\Administrator\Desktop\ymq\Domain-Aware-Style-Transfer-main\Domain-Aware-Style-Transfer-main\baseline.py", line 79, in __init__
    pretrained_vgg = torchfile.load('./baseline_checkpoints/vgg_normalised_conv4_1.t7')
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "D:\ANACONDA\envs\pytorch\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'

**Comment by Kibeom-Hong** [comment]
Thanks for your interesting!

I think you should check the path of 'pretrained_vgg'.

How about set the path as the absolute path?

Please check the code at 71 lines

Thanks.

**Comment by mamemo** [comment]
Hey guys, I just had the same issue. It's a Windows specific error. When running the code on Linux it outputs the desired results. 

Great work by the way!

**Comment by Pragathi-PL** [comment]
Yahh same error while running in mac
any idea how to resolve ?

**Comment by surfingnirvana** [comment]
fix for windows:

baseline.py

line 71             pretrained_vgg = torchfile.load('./baseline_checkpoints/vgg_normalised_conv4_1.t7', force_8bytes_long=True)
line 445           pretrained_vgg = torchfile.load('./baseline_checkpoints/vgg_normalised_conv4_1.t7', force_8bytes_long=True)

site-packages\torchfile.py", line 288                      for i in xrange(n):   ------------->    for i in range(n):
